export const categories = [
  {
    name: "Electronics",
    subcategories: [
      {
        label: "Mobiles & Accessories",
        items: [
          "Galaxy AI",
          "iPhones",
          "Premium Androids",
          "Tablets",
          "Headsets & Speakers",
          "Wearables",
          "Power Banks",
          "Chargers",
        ],
      },
      {
        label: "Laptops & Accessories",
        items: [
          "MacBooks",
          "Powerful Laptops",
          "Gaming Laptops",
          "Budget Laptops",
          "Monitors",
          "Printers",
          "Storage Devices",
          "Input Devices",
        ],
      },
      {
        label: "Gaming Essentials",
        items: [
          "Gaming Consoles",
          "Gaming Accessories",
          "Video Games",
          "Gaming Monitors",
          "Digital Cards",
        ],
      },
      {
        label: "TVs & Home Entertainment",
        items: [
          "LED",
          "QLED",
          "OLED",
          "4K",
          "8K",
          "Projectors",
          "Soundbars",
          "Streaming Devices",
        ],
      },
      {
        label: "Cameras",
        items: [
          "Action Cameras",
          "DSLR Cameras",
          "Surveillance Cameras",
          "Instant Cameras",
          "Camera Accessories",
        ],
      },
    ],
  },
  {
    name: "Men's Fashion",
    subcategories: [
      {
        label: "Clothing",
        items: [
          "T-shirts",
          "Polos",
          "Shirts",
          "Pants",
          "Jeans",
          "Sportswear",
          "Formal Wear",
          "Outerwear",
          "Underwear",
          "Socks",
        ],
      },
      {
        label: "Footwear",
        items: [
          "Sneakers",
          "Formal Shoes",
          "Sports Shoes",
          "Boots",
          "Loafers",
          "Sandals",
          "Flip Flops",
          "Slides",
        ],
      },
      {
        label: "Accessories",
        items: [
          "Watches",
          "Belts",
          "Wallets",
          "Ties",
          "Sunglasses",
          "Hats & Caps",
          "Backpacks",
          "Jewelry",
        ],
      },
      {
        label: "Grooming",
        items: [
          "Fragrances",
          "Skincare",
          "Haircare",
          "Shaving & Beard Care",
          "Body Care",
          "Grooming Kits",
        ],
      },
      {
        label: "Collections",
        items: [
          "Workwear",
          "Activewear",
          "Sleepwear",
          "Seasonal",
          "Designer",
          "Plus Size",
          "Sustainable",
        ],
      },
    ],
  },
  {
    name: "Women's Fashion",
    subcategories: [
      {
        label: "Spring/Summer",
        items: ["Tops", "Dresses", "Pants", "Sandals", "Skirts", "Swimwear"],
      },
      {
        label: "Clothing",
        items: [
          "Tops",
          "Dresses",
          "Pants",
          "Abayas & Jalabiyas",
          "Jeans",
          "Jumpsuits",
          "Sportswear",
        ],
      },
      {
        label: "Footwear",
        items: [
          "Sports shoes",
          "Sneakers",
          "Sandals",
          "Heels",
          "Flats",
          "Boots",
          "Flip flops",
          "Slides",
        ],
      },
      {
        label: "Bags & accessories",
        items: [
          "Backpacks",
          "Handbags",
          "Luggage",
          "Wallets",
          "Jewelry",
          "Laptop bags & cases",
          "Watches",
          "Eyewear",
        ],
      },
    ],
  },
  {
    name: "Kids' Fashion",
    subcategories: [
      {
        label: "Girls clothing",
        items: [
          "Tops",
          "Pants",
          "Clothing sets",
          "Dresses",
          "Onesies",
          "Sportswear",
          "Hoodies & sweatshirts",
        ],
      },
      {
        label: "Boys clothing",
        items: [
          "Tops and t-shirts",
          "Pants",
          "Clothing sets",
          "Onesies",
          "Sportswear",
          "Hoodies & sweatshirts",
        ],
      },
      {
        label: "Footwear",
        items: ["Sports shoes", "Sneakers", "Sandals", "Boots", "Flip flops"],
      },
      {
        label: "Bags & accessories",
        items: ["Backpacks", "Luggage", "Handbags", "Accessories"],
      },
    ],
  },
  {
    name: "Home & Kitchen",
    subcategories: [
      {
        label: "Kitchen & dining",
        items: [
          "Cookware",
          "Storage & organisation",
          "Dinnerware & serveware",
          "Accessories",
          "Cutlery",
          "Coffee & tea",
          "Bakeware",
          "Drinkware",
        ],
      },
      {
        label: "Furniture",
        items: [
          "Sofas & couches",
          "Coffee tables",
          "Gaming chairs",
          "Bean bags",
          "Desks & desk chairs",
          "TV & media units",
          "Storage & cabinets",
          "Chairs",
        ],
      },
      {
        label: "Tools & home improvement",
        items: [
          "Power tools",
          "Hand tools",
          "Cleaning supplies",
          "Home organisation",
          "Laundry care",
          "Safety & security",
          "Electrical & lighting",
          "Paints & wall supplies",
        ],
      },
      {
        label: "Home decor",
        items: [
          "Lighting",
          "Home fragrance",
          "Mats & carpets",
          "Furniture covers",
          "Mirrors",
          "Window treatments",
          "Decorative pillows",
          "Decor accents",
        ],
      },
      {
        label: "Bath & bedding",
        items: [
          "Sheets & Pillowcases",
          "Shower heads",
          "Comforter sets",
          "Duvet covers",
          "Towels",
          "Pillows",
          "Bath robes",
          "Bath organizers",
        ],
      },
      {
        label: "Home appliances",
        items: [
          "Air fryers",
          "Coffee makers",
          "Ovens & toasters",
          "Irons & steamers",
          "Blenders",
          "Vacuums",
          "Electric kettles",
          "Mixers",
        ],
      },
      {
        label: "Large appliances",
        items: [
          "Refrigerators",
          "Washing machines",
          "Air conditioners",
          "Cooking ranges",
          "Dishwashers",
          "Water dispensers",
          "Dryers",
          "Freezers",
        ],
      },
    ],
  },
  { name: "Beauty & Fragrance", subcategories: [] },
  { name: "Baby", subcategories: [] },
  { name: "Toys", subcategories: [] },
  { name: "Sports & Outdoors", subcategories: [] },
];

export const categories_carousel = [
  { name: "Appliances", image: "/images/appliances.png" },
  { name: "Health & Nutrition", image: "/images/health.png" },
  { name: "Toys & Games", image: "/images/toys.png" },
  { name: "Sports", image: "/images/sports.png" },
  { name: "Luggage", image: "/images/luggage.png" },
  { name: "Baby", image: "/images/baby.png" },
  { name: "Grocery", image: "/images/grocery.png" },
  { name: "Fragrances", image: "/images/fragrances.png" },
  { name: "Watches", image: "/images/watches.png" },
  { name: "Stationery", image: "/images/stationery.png" },
  { name: "Automotive", image: "/images/automotive.png" },
  { name: "Noon Gift Cards", image: "/images/giftcards.png" },
];

export const settings = {
  dots: true,
  autoplay: true,
  speed: 200,
  slidesToShow: 4,
  slidesToScroll: 4,
  autoplaySpeed: 2000,
  responsive: [
    { breakpoint: 1280, settings: { slidesToShow: 4 } },
    { breakpoint: 1024, settings: { slidesToShow: 3 } },
    { breakpoint: 768, settings: { slidesToShow: 2 } },
    { breakpoint: 480, settings: { slidesToShow: 1 } },
  ],
};

export const recommendations_carousel = [
  {
    image: "/images/appliances.png",
    name: "Samsung Galaxy S24 Ultra",
    rating: "4.6★ (6.8K)",
    originalPrice: "9,949 AED",
    discountedPrice: "2,999 AED",
    timeLeft: "GET IN 1 HR 3 MINS",
    bestSeller: true,
    stockInfo: "Selling out fast",
  },
  {
    image: "/images/health.png",
    name: "Apple iPhone 16 Pro Max",
    rating: "4.5★ (2.9K)",
    originalPrice: "5,999 AED",
    discountedPrice: "4,420 AED",
    timeLeft: "GET IN 1 HR 3 MINS",
    bestSeller: true,
    stockInfo: "Only 5 left in stock",
  },
  {
    image: "/images/health.png",
    name: "Apple iPhone 16 Pro Max",
    rating: "4.5★ (2.9K)",
    originalPrice: "5,999 AED",
    discountedPrice: "4,420 AED",
    timeLeft: "GET IN 1 HR 3 MINS",
    bestSeller: false,
    stockInfo: "Only 2 left in stock",
  },
  {
    image: "/images/health.png",
    name: "Apple iPhone 16 Pro Max",
    rating: "4.5★ (2.9K)",
    originalPrice: "5,999 AED",
    discountedPrice: "4,420 AED",
    timeLeft: "GET IN 1 HR 3 MINS",
    bestSeller: true,
    stockInfo: "In stock",
  },
  {
    image: "/images/health.png",
    name: "Apple iPhone 16 Pro Max",
    rating: "4.5★ (2.9K)",
    originalPrice: "5,999 AED",
    discountedPrice: "4,420 AED",
    timeLeft: "GET IN 1 HR 3 MINS",
    bestSeller: false,
    stockInfo: "Only 10 left in stock",
  },
  {
    image: "/images/health.png",
    name: "Apple iPhone 16 Pro Max",
    rating: "4.5★ (2.9K)",
    originalPrice: "5,999 AED",
    discountedPrice: "4,420 AED",
    timeLeft: "GET IN 1 HR 3 MINS",
    bestSeller: false,
    stockInfo: "Selling fast",
  },
];
